services:
  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: ecological_api
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - JWT_SECRET=${JWT_SECRET}

  ui:
    build:
      context: .
      dockerfile: Dockerfile.ui
    container_name: ecological_ui
    ports:
      - "8080:8080"
    depends_on:
      - api
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - BACKEND_URL=${BACKEND_URL}

volumes:
  mongo_data:
