version: "3.8"

services:
  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    container_name: ecological_test
    environment:
      - PYTHONPATH=/app:/app/ui
    volumes:
      - ./tests:/app/tests
      - ./ui:/app/ui
    command: ["python", "-m", "pytest", "tests/", "-v"]
