services:
  mongo:
    image: mongo:6
    container_name: ecological_mongo
    command: ["mongod", "--config", "/etc/mongod.conf"]
    ports:
      - "27017:27017"
    networks:
      - ecological-network
    volumes:
      - mongo_data:/data/db
      - ./mongod.conf:/etc/mongod.conf

  redis:
    image: redis:7
    container_name: ecological_redis
    ports:
      - "6379:6379"
    networks:
      - ecological-network
    volumes:
      - redis_data:/data

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: ecological_api
    volumes:
      - ./api/app:/app/app
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    command:
      [
        "uvicorn",
        "app.main:app",
        "--host",
        "0.0.0.0",
        "--port",
        "8000",
        "--reload",
      ]
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - JWT_SECRET=${JWT_SECRET}
      - BACKEND_REDIRECT_URL=${BACKEND_REDIRECT_URL}
      - FRONTEND_URL=${FRONTEND_URL}
      - GMAIL_APP_PASSWORD=${GMAIL_APP_PASSWORD}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - NOTION_TOKEN=${NOTION_TOKEN}
    tty: true
    stdin_open: true
    networks:
      - ecological-network
    develop:
      watch:
        - action: sync
          path: ./api
          target: /app
        - action: rebuild
          path: ./requirements.txt

  ui:
    build:
      context: .
      dockerfile: Dockerfile.ui
    container_name: ecological_ui
    volumes:
      - ./ui:/app/ui
    ports:
      - "8080:8080"
    depends_on:
      - api
      - redis
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - JWT_SECRET=${JWT_SECRET}
      - API_KEY=${API_KEY}
      - BACKEND_URL=${BACKEND_URL}
      - BACKEND_REDIRECT_URL=${BACKEND_REDIRECT_URL}
      - BASE_URL_SHARE=${BASE_URL_SHARE}
      # - UPSTASH_REDIS_REST_URL=${UPSTASH_REDIS_REST_URL} # only if testing Upstash Redis locally`
      # - UPSTASH_REDIS_REST_TOKEN=${UPSTASH_REDIS_REST_TOKEN} # only if testing Upstash Redis locally`
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    command: ["python", "ui/main.py"]
    tty: true
    stdin_open: true
    develop:
      watch:
        - action: sync
          path: ./ui
          target: /app
        - action: rebuild
          path: ./requirements.txt
    networks:
      - ecological-network

volumes:
  mongo_data:
  redis_data:

networks:
  ecological-network:
    driver: bridge
