# Dockerfile.ui
FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt .

# Install curl and any necessary dependencies
RUN apt-get update && apt-get install -y curl && \
    pip install --no-cache-dir -r requirements.txt && \
    apt-get clean && rm -rf /var/lib/apt/lists/*


COPY ui /app/ui
COPY static /app/static

CMD ["python", "ui/main.py"]
