services:
  - type: web
    name: ecological-journey
    env: docker
    repo: https://github.com/jshreyas/ecological_journey
    dockerfilePath: Dockerfile.ui
    buildFilter:
      paths:
        - ui/**
        - Dockerfile.ui
        - requirements.txt
    autoDeploy: true
    plan: free
    envVars:
      - key: JWT_SECRET
        sync: false
