# render.yaml
services:
  - type: web
    name: ecological-journey-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: MONGODB_URI
        value: your-mongodb-uri-here
      - key: SECRET_KEY
        value: your-secret-key-here
    plan: free
