services:
  - type: web
    name: ecological-journey-api
    env: docker
    repo: https://github.com/jshreyas/ecological_journey
    dockerfilePath: Dockerfile.api
    buildFilter:
      paths:
        - api/**
        - Dockerfile.api
        - requirements.txt
    autoDeploy: true
    plan: free
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false

  - type: web
    name: ecological-journey
    env: docker
    repo: https://github.com/jshreyas/ecological_journey
    dockerfilePath: Dockerfile.ui
    buildFilter:
      paths:
        - ui/**
        - Dockerfile.ui
        - requirements.txt
    autoDeploy: true
    plan: free
    envVars:
      - key: JWT_SECRET
        sync: false
      - key: BACKEND_URL
        sync: false
