# .github/workflows/ping_render.yaml
name: Ping Render Apps

# on:
#   schedule:
#     - cron: '*/15 * * * *'  # every 15 minutes, all day, every day (UTC)
#   workflow_dispatch:  # allows manual triggering from GitHub UI

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping UI
        run: curl -s https://ecological-journey.onrender.com > /dev/null

      - name: Ping API
        run: curl -s https://ecological-journey-api.onrender.com > /dev/null
