# .github/workflows/ping_render.yaml
name: Wake up Ecological Journey

on:
  schedule:
    - cron: "*/5 12-13 * * *"  # every 5 mins during 5–7 AM PST
  workflow_dispatch:  # allows manual triggering from GitHub UI

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: curl Ecological Journey
        run: curl -v https://ecological-journey.onrender.com
